CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS firms_detections (
    id           BIGSERIAL                  PRIMARY KEY,
    acq_datetime TIMESTAMPTZ                NOT NULL,
    geom         GEOGRAPHY(POINT, 4326)     NOT NULL,
    latitude     DOUBLE PRECISION           NOT NULL,
    longitude    DOUBLE PRECISION           NOT NULL,
    bright_ti4   REAL,
    bright_ti5   REAL,
    frp          REAL,
    scan         REAL,
    track        REAL,
    satellite    VARCHAR(10),
    confidence   VARCHAR(10),
    daynight     CHAR(1),
    type         SMALLINT,
    version      VARCHAR(10),
    ingested_at  TIMESTAMPTZ                NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS firms_detections_geom_idx
    ON firms_detections USING GIST (geom);

CREATE INDEX IF NOT EXISTS firms_detections_acq_datetime_idx
    ON firms_detections (acq_datetime);

-- Phase 2: GDELT events (filtered to CAMEO 190x/193x/195x, ActionGeo_Type 3/4)
CREATE TABLE IF NOT EXISTS gdelt_events (
    id                  BIGSERIAL                  PRIMARY KEY,
    global_event_id     BIGINT                     NOT NULL UNIQUE,
    event_date          DATE                       NOT NULL,
    event_datetime      TIMESTAMPTZ                NOT NULL,
    cameo_code          VARCHAR(10)                NOT NULL,
    cameo_root          SMALLINT,
    goldstein_scale     REAL,
    num_mentions        INTEGER,
    num_sources         INTEGER,
    avg_tone            REAL,
    actor1_name         TEXT,
    actor2_name         TEXT,
    action_geo_type     SMALLINT                   NOT NULL,
    action_geo_fullname TEXT,
    action_geo_country  VARCHAR(5),
    geom                GEOGRAPHY(POINT, 4326)     NOT NULL,
    latitude            DOUBLE PRECISION           NOT NULL,
    longitude           DOUBLE PRECISION           NOT NULL,
    source_url          TEXT,
    ingested_at         TIMESTAMPTZ                NOT NULL DEFAULT NOW()
);

-- Idempotent migration: add source_url to existing tables created before this column existed.
ALTER TABLE gdelt_events ADD COLUMN IF NOT EXISTS source_url TEXT;

CREATE INDEX IF NOT EXISTS gdelt_events_geom_idx
    ON gdelt_events USING GIST (geom);
CREATE INDEX IF NOT EXISTS gdelt_events_datetime_idx
    ON gdelt_events (event_datetime);
CREATE INDEX IF NOT EXISTS gdelt_events_cameo_idx
    ON gdelt_events (cameo_code);

-- Phase 2: many-to-many correlation pairs
CREATE TABLE IF NOT EXISTS fire_event_correlations (
    id                  BIGSERIAL   PRIMARY KEY,
    firms_detection_id  BIGINT      NOT NULL REFERENCES firms_detections(id),
    gdelt_event_id      BIGINT      NOT NULL REFERENCES gdelt_events(id),
    distance_m          REAL        NOT NULL,
    time_delta_h        REAL        NOT NULL,   -- negative = event published before fire detected
    score               REAL        NOT NULL,
    infra_id            BIGINT,                 -- FK reserved for Phase 3; NULL in Phase 2
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (firms_detection_id, gdelt_event_id)
);

CREATE INDEX IF NOT EXISTS fec_firms_idx
    ON fire_event_correlations (firms_detection_id);
CREATE INDEX IF NOT EXISTS fec_gdelt_idx
    ON fire_event_correlations (gdelt_event_id);
CREATE INDEX IF NOT EXISTS fec_score_idx
    ON fire_event_correlations (score DESC);

-- Phase 4: 7-day deduplicated FIRMS snapshot, regenerated by spark_pipeline.py.
-- id mirrors firms_detections.id; geom is populated by psycopg2 after JDBC write.
CREATE TABLE IF NOT EXISTS firms_silver (
    id           BIGINT                     PRIMARY KEY,
    acq_datetime TIMESTAMPTZ                NOT NULL,
    geom         GEOGRAPHY(POINT, 4326),
    latitude     DOUBLE PRECISION           NOT NULL,
    longitude    DOUBLE PRECISION           NOT NULL,
    bright_ti4   REAL,
    bright_ti5   REAL,
    frp          REAL,
    scan         REAL,
    track        REAL,
    satellite    VARCHAR(10),
    confidence   VARCHAR(10),
    daynight     CHAR(1),
    type         SMALLINT,
    version      VARCHAR(10),
    ingested_at  TIMESTAMPTZ                NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS firms_silver_geom_idx
    ON firms_silver USING GIST (geom);

CREATE INDEX IF NOT EXISTS firms_silver_acq_datetime_idx
    ON firms_silver (acq_datetime);
